### PR TITLE
[Comgr] Fix metadata merge failure when multiple notes have amdhsa.printf

### PR DESCRIPTION
**Pull request by yxsamliu**
With the new offload driver, LLD uses --lto-partitions=8, splitting the device module into multiple LTO partitions. Each partition is compiled independently by the AMDGPU backend, producing its own NT_AMDGPU_METADATA note. When -mprintf-kind=buffered is used, every note contains an amdhsa.printf section.

The amdhsa.printf content is identical across all partitions because SplitModule uses CloneModule, which copies all named metadata (including llvm.printf.fmts) to every partition. The AMDGPU backend's emitPrintf() then emits the full format string list into each partition's note.

mergeNoteRecords() previously rejected the merge when both the accumulated root and the incoming note had amdhsa.printf, causing only the first partition's kernel to be visible. All subsequent kernels triggered "Cannot find Symbol" at runtime.

Fix by allowing the merge when both notes have identical amdhsa.printf, and rejecting only when they differ to preserve correctness.

Fixes: LCOMPILER-553

### CODE REVIEW

**Comment by z1-cciauto** [comment]
PSDB Build Link: http://mlse-bdc-20dd129:8065/#/builders/11/builds/14

**Review by lamb-j — APPROVED** [review]

**Comment by z1-cciauto** [comment]
PSDB Build Link: http://mlse-bdc-20dd129:8065/#/builders/11/builds/21

**Comment by yxsamliu** [comment]
Reopening with branch pushed directly to ROCm repo (not fork) to fix RockCI credential validation. Previous review: #1665
