### PR TITLE
[Comgr] Fix Windows build: use LLVM_ATTRIBUTE_WEAK for hotswap stubs

### PR DESCRIPTION
**Pull request by lamb-j**
## Summary

PR #2203 introduced 15 weak-symbol patch / liveness / DWARF stubs in `comgr-hotswap-b0a0.cpp` using GCC/Clang attribute syntax:

```cpp
__attribute__((weak)) uint32_t applyInPlacePatches(PatchContext &, size_t) {
  return 0;
}
```

MSVC does not understand this. It tokenizes `__attribute__` as an identifier and `weak` as undeclared, then errors on every weak stub:

```
comgr-hotswap-b0a0.cpp(95): error C2065: 'weak': undeclared identifier
comgr-hotswap-b0a0.cpp(95): error C2374: '__attribute__': redefinition
[...repeats for every weak stub at lines 95, 98, 101, 104, 107, 117,
 123, 135, 141, 143, 152, 157, 162, 164, 166...]
```

This PR replaces the raw GCC attribute with LLVM's portable `LLVM_ATTRIBUTE_WEAK` macro from `llvm/Support/Compiler.h`. On Linux/macOS it expands to `__attribute__((__weak__))` (current behaviour preserved); on Windows it expands to nothing — the symbols become regular strong symbols, which compiles fine because `comgr-hotswap-b0a0.cpp` is currently the only TU defining these names.

Failing Windows job from PR #2203: https://github.com/ROCm/llvm-project/actions/runs/24758866527/job/72438109210

## Scope

Immediate Windows unblock only. The weak-symbol pattern was chosen so follow-up patch PRs (#2222 in-place patches, future trampoline / WMMA / scratch) can each provide strong-symbol overrides without merge conflicts. On Windows, that overriding mechanism does not work — when a follow-up PR adds a strong override of one of these stubs, both TUs will emit a strong symbol and the linker will fail with a duplicate-symbol error.

A follow-up is needed to address the override pattern on Windows, options including:
- Function-pointer registration where each patch module registers its override in a static initializer
- `__declspec(selectany)` (with care — semantics differ from Unix weak)
- `#ifdef`-out the patch overrides on MSVC (degraded but compiles)

Out of scope for this PR.

### CODE REVIEW

**Comment by z1-cciauto** [comment]
PSDB Link: https://compiler-ci.amd.com/job/compiler-psdb-amd-staging/5407

**Review by chinmaydd — APPROVED** [review]
Should have caught this, thanks !

**Comment by ronlieb** [comment]
passing relevant aspects . windows ci
